Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update -y
    sudo apt install -y python3 python3-pip python3-venv
    sudo apt install -y redis-server
    python3 -m venv v
    . ./v/bin/activate
    pip install -U pip 'celery[redis]'
    cat <<EOS> tasks.py
import os
from celery import Celery

import time

app = Celery()
app.conf.broker_url = 'redis://localhost:6379/0'
app.conf.result_backend = 'redis://localhost:6379/0'

@app.task
def hello():
    time.sleep(5)
    return os.getpid()
EOS
    sudo cat <<EOF> /etc/systemd/system/celery.service
[Unit]
Description=celery daemon

[Service]
Type=simple
User=vagrant
Group=vagrant
WorkingDirectory=/home/vagrant
ExecStart=/home/vagrant/v/bin/celery -A tasks worker --concurrency=2
Restart=on-failure
[Install]
WantedBy=multi-user.target
EOF
    sudo systemctl daemon-reload
    sudo systemctl start celery
  SHELL
end
