Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network :forwarded_port, host: 5555, guest: 5555
  config.vm.synced_folder ".", "/vagrant/"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update -y
    sudo apt install -y python3 python3-pip python3-venv
    sudo apt install -y redis-server

    sudo pip3 install -U pip
    python3 -m venv /home/vagrant/venv
    . /home/vagrant/venv/bin/activate
    pip install -r /vagrant/requirements.txt

    celery worker --app tasks --concurrency 2 --loglevel=INFO -f celery.log &
    celery flower --app tasks &

    cp /vagrant/tasks.py .
    for i in {0..10}; do python -c 'from tasks import hello; print(hello.apply_async())'; done

    # kill celery process
    # ps aux|grep -v grep | grep celery | awk '{print $2}' | xargs kill -9
  SHELL
end
